language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  postgresql: 9.3
  apt:
    sources:
      - pov-wkhtmltopdf
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-serial
      - python-yaml
      - wkhtmltopdf
      - libgeos-dev
      - postgis
      - postgresql-9.3-postgis-scripts
      - postgresql-9.3-postgis-2.3

before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/Jarsa/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - if [[ "${OCA_RUNBOT}" == "1" ]]; then git clone --depth=1 git@github.com:odoo/enterprise.git -b $VERSION ${HOME}/enterprise; fi
  - travis_install_nightly

before_script:
  - psql -c 'CREATE DATABASE template_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d template_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d template_postgis
  - psql -c 'ALTER ROLE travis SUPERUSER;' -U postgres
  - export DATABASE_URL="postgis://travis:@127.0.0.1:5432/stoqs"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success